# Generated by Django 5.0.7 on 2024-09-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aberturasportas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='acessosapp',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='agendamentohorarios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='agendamentos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='apartamentos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='areas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='areasparalelas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='atendimentos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='atividades',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='atividadesmateriaisprodutos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='atividadesordemdeservicos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authgroup',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authgrouppermissions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authpermission',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authusergroups',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authuseruserpermissions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='camfacials',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cardselevadors',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='centraisjfls',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='chamadas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='chavesvirtuais',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='checklistobras',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='codigos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comercialetapas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comercialleadetapas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comercialleadprocessos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comercialleads',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comercialprocessos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comercialprospeccao',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comodatos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='condominioequipamentos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='condominios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='condominiosferiados',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='condominiosfuncionarios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='condominiosfuncionariosdispositivosroles',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='configfacials',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='configos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='contatoemergencias',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='controlesacessos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='convidados',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='criticidades',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='departamentos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dispositivos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dispositivosacessos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dispositivoscards',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dispositivoscardstipos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dispositivoseventos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dispositivosmarcas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dispositivosmodelos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dispositivosregistros',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dispositivosroles',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dispositivosrolesdispositivosacessos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dispositivostipos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangoadminlog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangocontenttype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangosession',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='documentos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='elevadorchamados',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='empresas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='empresasservicos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='empresasservicosempresas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='encomendas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='entregadoresnormas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='estadosequipamentos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='eventos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='eventostratados',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='faturamentos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='faturamentosmateriais',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='faturamentosorcamentos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='feriados',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ferramentas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fotos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='funcionarios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='gruposeventos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='gruposzonas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='historicocondominios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='historicopessoas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='imagemcameras',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='informativos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='internets',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='itenscadastrados',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='itensorcamentos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='itensvistorias',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='liberacoesacessos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='liberacoeschaves',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='materiaisatividades',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='materiaisgrupos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='materiaismarcas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='materiaisobras',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='materiaisprodutos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='materiaisunidades',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mudancasnormas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='notificacoes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='obras',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='obraschecklistobras',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ocorrencias',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='orcamentos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='orcamentosmateriais',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='orcamentospessoas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ordemdeservicos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ordemdeservicosmateriaisprodutos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='parcelas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='patrimonios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pedagios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='permissaoacessos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='permissaoacessosdispositivosroles',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pessoas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pessoasdispositivosroles',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pets',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pgms',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='plantaoocorrencias',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='plantaooperacionals',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='portas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='prestadoresacessos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='prestadoresnormas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='projetos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='qths',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='qthstarefas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='qthstarefasqths',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='questionarios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='racas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='recados',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='reconhecidofacials',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='reservasnormas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sindicos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subramais',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subtiposocorrencias',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subtiposocorrenciasocorrencias',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subtipostiposabastecimentos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='suporteunidades',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tarefas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tatticafuncionarios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tatticatelefones',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tiposacessos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tiposclassificacaos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tiposcondominiosfuncionarios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tiposcontrolesacessos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tiposelevadorchamados',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tiposencomendas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tiposequipamentos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tiposeventos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tiposeventostratados',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tiposfotos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tiposfuncionarios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tiposocorrencias',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tiposocorrenciasocorrencias',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipospagamentos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipospatrimonios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipospedagios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipospessoas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tiposprojetos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tiposracas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipossindicos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipostarefas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tiposveiculos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tiposzonas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tips',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipstatticafuncionarios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='unidades',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='vagas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='veiculos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='vistorias',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='vistoriasitensvistorias',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='zonas',
            options={'managed': True},
        ),
    ]
